### ISSUE TITLE
make web ui less shitty

### ISSUE THREAD

**Issue by choochootrain** [SharangP/ideas#5]
mebbe use mithril.js? very cool very gzip wow such lightweight many render such react

**Comment by choochootrain** [comment]
- search box
- add from web ui
- filter by tags and shit
- use sqlite and dump to yaml in pre-commit hook

**Comment by jonathan-ostrander** [comment]
#raped

**Comment by jonathan-ostrander** [comment]
Should we say fuck you to jinja?

**Comment by choochootrain** [comment]
https://github.com/lhorie/mithril.js

this shit

**Comment by choochootrain** [comment]
also fuk u dis mine

**Comment by choochootrain** [comment]
u wot m8

**Comment by choochootrain** [comment]
cheeky cunt hav a go and ill chop yer gabber off

**Comment by SharangP** [comment]
@choochootrain i dont want to spin the app just to add a new idea. unless this is going to run somewhere permanently

**Comment by choochootrain** [comment]
I think it should run somewhere permanently. Most of my shitty ideas come
when I'm not at a gittable computer so this would be v nice

It'll dump to yaml at commit time so you'll be able to work on it from the
web ui or git it don't care

**Comment by jonathan-ostrander** [comment]
why not just throw it up on heroku and add an ezpz cms?

**Comment by choochootrain** [comment]
I think it should be version controlled so we should back it with this repo
in either case

**Comment by SharangP** [comment]
where is it going to run permanently?
commit hook sounds like it'll work - it has to sync in both directions tho.

**Comment by SharangP** [comment]
also why are you making a mega ticket this should be at least 3 tickets you fuck

**Comment by jonathan-ostrander** [comment]
mega ticket best ticket.  also, this sounds much more complicated than it needs to be.  why not edit the yaml on github if you're not at a gittable computer?  Adding search/filter and tags is ezpz but we need to figure out if we're making this change or not.

**Comment by choochootrain** [comment]
yea editing on github is fine but i always forget me password. this is low pri we should be shitting out ideas first and web ui-ing second

**Comment by jonathan-ostrander** [comment]
![monitor-throw-maurice-moss-the-it-crowd](https://cloud.githubusercontent.com/assets/5961416/14122122/3ec78844-f5c8-11e5-8994-ae9c69e65690.gif)

**Comment by choochootrain** [comment]
agreed this is stale task. closing because fuck you i'm a pm now
